version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
